name: multiscalemae
channels:
  - pytorch
  - nvidia
  - free
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip
  - numpy=1.21.0
  - pandas=1.5.3
  - scipy=1.10.1
  - scikit-learn=1.5.1
  - scikit-image=0.19.3
  - seaborn=0.12.2
  - matplotlib=3.6.3
  - tqdm=4.64.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.7
  - zarr=2.13.6
  - anndata=0.8.0
  - scanpy=1.9.2
  - leidenalg=0.9.1
  - igraph=0.10.3
  - h5py=3.8.0
  - umap-learn=0.5.3
  - yaml=0.2.5
  - xz=5.2.10
  - zstandard=0.19.0
  - libgcc-ng=12.2.0
  - libstdcxx-ng=12.2.0
  - pip:
      - einops==0.6.1
      - timm==0.3.2
      - tensorboard==2.17.1
      - wandb==0.13.9
      - cython==3.0.11
      - llvmlite==0.38.0
      - numba==0.55.0
      - torch==1.13.1
      - torchvision==0.14.1
      - torchaudio==0.13.1
      - protobuf==4.21.12
      - psutil==5.9.4
      - pyyaml==6.0
      - setuptools==65.6.3
      - pip==22.3.1
      - requests==2.28.1
      - tqdm==4.64.1
      - umap-learn==0.5.3
      - imageio==2.25.0
      - tifffile==2021.11.2
      - zipp==3.15.0
      - dask==2023.1.1
      - cloudpickle==2.2.1
      - toolz==0.12.0
      - networkx==3.0
      - fasteners==0.17.3
      - h5py==3.8.0
      - grpcio==1.66.1
      - markdown==3.7
      - werkzeug==3.0.4
